import { ExampleData } from './types';

export const exampleData: ExampleData[] = [
  {
    id: '1',
    title: 'Title 1',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'primary',
    variant: 'contained',
  },
  {
    id: '2',
    title: 'Title 2',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'secondary',
    variant: 'contained',
  },
  {
    id: '3',
    title: 'Title 3',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'success',
    variant: 'contained',
  },
  {
    id: '4',
    title: 'Title 4',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'negative',
    variant: 'contained',
  },
  {
    id: '5',
    title: 'Title 5',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'warning',
    variant: 'contained',
  },
  {
    id: '6',
    title: 'Title 6',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'primary',
    variant: 'outlined',
  },
  {
    id: '7',
    title: 'Title 7',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'secondary',
    variant: 'outlined',
  },
  {
    id: '8',
    title: 'Title 8',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'success',
    variant: 'outlined',
  },
  {
    id: '9',
    title: 'Title 9',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'negative',
    variant: 'outlined',
  },
  {
    id: '10',
    title: 'Title 10',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'warning',
    variant: 'outlined',
  },
  {
    id: '11',
    title: 'Title 11',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'primary',
    variant: 'text',
  },
  {
    id: '12',
    title: 'Title 12',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'secondary',
    variant: 'text',
  },
  {
    id: '13',
    title: 'Title 13',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'success',
    variant: 'text',
  },
  {
    id: '14',
    title: 'Title 14',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'negative',
    variant: 'text',
  },
  {
    id: '15',
    title: 'Title 15',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit.',
    date: new Date().toLocaleString(),
    color: 'warning',
    variant: 'text',
  },
];

export const textContent =
  'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero sit labore, quidem beatae necessitatibus excepturi, fugit distinctio quis dolores quos numquam animi obcaecati odio sequi quasi natus.';
